### PR TITLE
github actions

### PR DESCRIPTION
**Pull request by zitrosolrac**

### CODE REVIEW

**Review by guzman-raphael — CHANGES_REQUESTED** [review]
Nice work @zitrosolrac! 👏

Can you just rename the GH Actions workflow to `development.yaml` and make sure they that the `gh-pages` branch exists before the merge? Also, we'll need to tagup to add the DNS entry together.

**Comment by zitrosolrac** [comment]
sure! you can ping me whenever you're ready to tag up!

**Comment by zitrosolrac** [comment]
I've checked and the `upstream` repo seems to already have a `gh-pages` branch.

**Review by guzman-raphael — APPROVED** [review]
@zitrosolrac Good stuff! :+1:

**Pull request merged**
